### ISSUE TITLE
Changing a calendar's color shifts all associated events into the future

### ISSUE THREAD

**Issue by ctruett** [solspace/craft3-calendar#236]
**Describe the bug or issue you're experiencing**
Events are no longer visible in the Month / Week / etc. views in the backend after changing the calendar's color.

**Steps to reproduce**

1. Create a calendar
2. Duplicate the calendar, change the name
3. Add events to the calendars
4. Change the color of one of the calendars

**Expected behavior**
Events should be visible ·͜·

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.2 (Solo)
- Calendar Version: 4.0.9
- Calendar Edition: Pro (trial)
- Fresh Install or Upgrade: Fresh install

**Additional context**

**Comment by ctruett** [comment]
The issue is actually that all my events' dates were moved somehow between 2-5 years into the future upon changing the color of the calendar they belong to.

**Comment by ctruett** [comment]
Noted that it happens whenever I change just about anything on the calendar's setting page.

**Comment by kjmartens** [comment]
I'm very sorry for the trouble you're experiencing, @ctruett.

We are investigating this issue now.

**Comment by kjmartens** [comment]
@ctruett In your testing, does it appear that it does the following:

1. Only affects repeating/recurring events.
2. It sets the Start Date/End Date for the very last available recurrence before the End Repeat date.

Are you observing this as well? Any other patterns? 🙂

**Comment by ctruett** [comment]
1. Yes
2. That seems to be the case. All the affected events do not have an specified end date.

**Comment by ctruett** [comment]
Forgot to tag you in my previous comment, apologies @kjmartens !

**Comment by kjmartens** [comment]
Sorry for the delay, @ctruett. This is queued up for a developer to have addressed by next week.

**Comment by kjmartens** [comment]
This is now resolved in Calendar 4.0.10+.

Sorry for the delay.

**Comment by outline4** [comment]
Hi, unlucky I experience the same issue. Each time I save a calendar it moves all entries one year into the future?! 

Before: 

<img width="1106" alt="Bildschirmfoto 2023-11-28 um 23 54 50" src="https://github.com/solspace/craft-calendar/assets/145828/b91b959b-899d-459a-920a-ed06563c49ac">

After: 

<img width="1110" alt="Bildschirmfoto 2023-11-28 um 23 55 21" src="https://github.com/solspace/craft-calendar/assets/145828/f3ae4e3c-ee28-48e5-817e-74b5c554bfb9">

And yes: it only occurs on repeating events. 

This would be an absolute catastrophe if this would happen on a live site! 

PHP version: 8.2.12   
Craft edition & version	Craft Pro 4.5.11.1  
Kalender	4.0.9

**Oops:**  
I see that I am on calendar 4.0.9 and it should be fixed in 4.0.10+, but the version 4.0.9 is the latest that you offer. When is .10 coming out?

**Comment by kjmartens** [comment]
@outline4 Something went wrong with the connection between our repo and Craft, so the version didn't sync for some reason. Craft has manually resolved the issue now, so go ahead and try out 4.0.10+. 🙂

**Comment by outline4** [comment]
I am sorry to say, but this is still not fixed. 

I just updated the plugin to 4.0.11 and changed the color of the calendar and it shifts the date for one year: 

Original:  

<img width="847" alt="Bildschirmfoto 2023-11-30 um 10 19 55" src="https://github.com/solspace/craft-calendar/assets/145828/ce25c50d-3af2-499e-b191-44dabe350e4f">

After changing the color: 

<img width="851" alt="Bildschirmfoto 2023-11-30 um 10 21 46" src="https://github.com/solspace/craft-calendar/assets/145828/4623feb7-50e8-4f93-9b15-8126222f3a65">

Original: 

<img width="701" alt="Bildschirmfoto 2023-11-30 um 10 20 13" src="https://github.com/solspace/craft-calendar/assets/145828/85c07baa-9da0-4868-a19e-fad7897cd085">

After changing the color: 

<img width="688" alt="Bildschirmfoto 2023-11-30 um 10 22 11" src="https://github.com/solspace/craft-calendar/assets/145828/f3396efe-a6c3-4bae-8f9c-710fbd057f16">

This is something that would be very very annoying, because in about a month we will have tons of these events... 

I hope you can fix this for good. 

Is there anything I can help?

**Comment by outline4** [comment]
**bump** since it still happens with some events. Even on calendar 4.0.11. 

This is rather important, isn't it?

**Comment by kjmartens** [comment]
Sorry for the delay, @outline4.

I have set up a new calendar with a large variety of test events and tried to replicate the issue on Calendar 4.0.11+ and I can't. It doesn't happen for me since the fix. 🙂 

Are you 100% sure you're using 4.0.11? And just to clarify, the fix will not be retroactive - any events that were affected by this issue in 4.0.9 and below. It will just prevent it from happening to future events when a calendar is updated.

**Comment by outline4** [comment]
Ok, I didn't know that I have to re-enter all events that are affected!  
And I am absolutely sure that I use calendar 4.0.11.  

So I've re-entered an event that was concerned. 

The error on this particular event still exists, but it's different. 

Please compare: 

Here's the event that I already had entered with version 4.0.9:

Before resaving the calendar: 

<img width="651" alt="Bildschirmfoto 2024-01-10 um 19 46 21" src="https://github.com/solspace/craft-calendar/assets/145828/a1ce8828-8943-4d03-9de9-d23e97ed3983">

after resaving the calendar: 

<img width="658" alt="Bildschirmfoto 2024-01-10 um 19 47 43" src="https://github.com/solspace/craft-calendar/assets/145828/f7d9032b-1d8d-4345-af11-e74e1aedcd7e">

(it shifted the start date for one year)


Now the exact same event I've entered on calendar 4.0.11:

Before resaving the calendar: 

<img width="646" alt="Bildschirmfoto 2024-01-10 um 19 46 03" src="https://github.com/solspace/craft-calendar/assets/145828/faf38933-4dd1-4962-a247-42bb1faf11a7">

after resaving the calendar: 

<img width="662" alt="Bildschirmfoto 2024-01-10 um 19 47 33" src="https://github.com/solspace/craft-calendar/assets/145828/dc6ddbbc-229a-47ed-9c58-06f98d1a450c">

(it shifted the event 9 month und 23 days or 297 days)

Now: can you please confirm that you also get the same error in this particular case? 

And: is there a way around having to recreate these events? E.g. duplicate them? 

I hope this will get fixed soon!

**Comment by kjmartens** [comment]
@outline4,

I was not observing anything like this. Just to confirm, the steps you took were as follows? 🙂 

1. Update to (or already be on) Calendar 4.0.11.
2. Create a new event (not duplicate or clone or edit an existing one - not that it should matter, but I am curious).
3. Configure the date and such as seen in the screenshot. Save the event.
4. Edit the calendar's color and save.

**Comment by outline4** [comment]
Hi Kelsey, 

That's exactely what I did. 

The event with (x) was already there in 4.0.9

The event with (neu) was created freshly in 4.0.11

Have you really tried the exact same date?



this is my install: 

PHP version 	8.2.0  
OS version 	Darwin 21.6.0  
Database driver & version 	MySQL 5.7.39  
Image driver & version 	Imagick 3.7.0 (ImageMagick 6.9.6-2)  
Craft edition & version 	Craft Pro 4.5.13  
Yii version 	2.0.48.1  
Twig version 	v3.4.3  
Guzzle version 	7.8.1  

Plug-ins  
Campaign	2.12.0  
CKEditor	3.6.0  
Contact Form	3.0.1  
Control Panel CSS	2.6.0  
Control Panel JS	2.6.0  
Dashboard Begone	2.0.0  
Dumper	3.0.1  
Empty Coalesce	4.0.0  
Kalender	4.0.11  
MailerSend	1.0.1  
PathTools	4.0.0-beta.1  
Style Inliner	3.0.5  
Super Table	3.0.12  
Template Selector	1.0.7

**Comment by outline4** [comment]
How can we proceed?  
Could I send you my db and composer.json?

**Comment by ctruett** [comment]
Unfortunately, this issue is still happening on 4.0.11.

Brand new calendar, brand new events.

Create events, then go change a setting (any setting, as far as I can tell, but most recently it was switching to a fixed time zone instead of a floating one) on the corresponding calendar page and it pushes all events six months into the future. 

At this point the plugin basically useless to me as I need to edit many events any time I change a calendar setting.

Another symptom I have noticed is that events show on the wrong day. I'll set it for Friday, but it will render on the frontend as Thursday. Currently working around this with `startDateLocalized`.

@kjmartens any thoughts / fixes?

**Comment by kjmartens** [comment]
Sorry for the delay everyone.

This should be resolved now in Calendar 4.0.12+. 🙂
